### ISSUE TITLE
HyperCeiler缺少禁止临时关闭蓝牙功能

### ISSUE THREAD

**Issue by long239** [Xposed-Modules-Repo/com.sevtinge.hyperceiler#4]
在早期西米露的设置中，可以禁止临时关闭蓝牙，但在某次更新后，禁止临时关闭蓝牙的项目被隐藏了（作为对比，从未恢复出厂设置的K60自MIUI14保留下来的设置可以在没有更改情况下保留禁止临时关闭蓝牙），Civi3在重置后无法从软件里找到禁止临时关闭蓝牙，我认为这对设备使用者非常有用，这个功能应当被重视。谢谢。

**Comment by mu7220** [comment]
未缺失过，已挪动到 系统界面-其他 分类
处于 Xiaomi HyperOS 的设备将默认隐藏（因系统提供此功能）
